name: ci
on: push

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: qniu/chicken-unit-test
      env:
        SRC: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodule: recursive
      - name: Run Tests
        run: /run.sh
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: /test_output/*