name: build docker image

on:
  pull_request:
    branches:
      - docker


jobs:
  release-docker-image:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        image: [chicken-builder, chicken-style, chicken-unit-test]
        include:
          - image: chicken-builder
            context: docker/builder
            file: docker/builder/Dockerfile
          - image: chicken-style
            context: docker/style
            file: docker/style/Dockerfile
          - image: chicken-unit-test
            context: docker/test/unittest
            file: docker/test/unittest/Dockerfile

    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          submodule: recursive

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build_builder_image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image }}:v0.1,${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}