name: build docker image

on:
  push:
    branches:
      - docker

inputs:
  tag:
    description: 'docker image tag'
    default: 'dev'
    required: true
    type: string

jobs:
  release-docker-image:
    strategy:
      fail-fast: false
      matrix:
        image: [builder, style]
        include:
          - image: builder
            context: docker/builder
            file: docker/builder/Dockerfile
        
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build_builder_image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image }}:${{ inputs.tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}