name: unit test
on: pull_request

jobs:
  unit_test:
    uses: mrssss/run-test-action/.github/workflows/run_dockerfile.yml@main
    with:
      dockerfile: docker/test/unittest/Dockerfile
      context-directory: docker/test/unittest/
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
