name: do-the-job
on: push
jobs:
  run_test:
    uses: mrssss/run-test-action/action.yml@main
    with:
      dockerfile: docker/test/unittest/Dockerfile
      context-directory: docker/test/unittest/
      args: '-v .:/source'