name: unit-test
on: pull_request

jobs:
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: qniu/chicken-unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run Tests
        run: SRC=${GITHUB_WORKSPACE} /run.sh
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: /test_output/*